# Site/SEO settings
email: mwlaugh@gmail.com
baseurl: "www.mwinslow.com"
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Mark Laughery
title: Portfolio for Mark Laughery
description: >
  Designer and stuff
url: http://www.mwinslow.com
twitter_username: mlaugh4
default_img: /assets/images/placeholder-24.jpg
social:
  - name: twitter
    url: https://twitter.com/mlaugh4
  - name: instagram
    url: https://www.instagram.com/mlaugh4/
  - name: linkedin
    url: https://www.linkedin.com/in/marklaughery/
  - name: github
    url: https://
  - name: codepen
    url: https://

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Mark Laughery
    bio: Mark Laughery was born in Seattle and has lived in New York, LA, Austin, Nairobi, and Bangkok. He currently lives in Tokyo.
    url: http://mwinslow.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
